apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: pypi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
status: {}
